"""Canonical dataset schema (`vakforge.jsonl`). Source of truth for docs/DATA_FORMAT.md.

Structural rules that need only the record itself live here as pydantic validators.
Rules that need the filesystem or the locale registry live in `vakforge.validate`.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import PurePosixPath, PureWindowsPath
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION = "0.1"

Speaker = Literal["user", "agent", "tool"]
Condition = Literal["studio", "clean", "phone", "noisy"]
Source = Literal["real", "synthetic", "public"]
Consent = Literal["recorded_verbal", "written", "synthetic", "public_license", "none"]
AllowedUse = Literal["asr", "workflow", "evaluation", "voice_clone"]
Split = Literal["train", "val", "test"]


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


def dataset_relative(value: str, field: str) -> str:
    """Reject a path that could point outside the dataset, or raise saying why.

    A manifest is data: generated by a pipeline, downloaded, or handed over with a dataset.
    Every path it carries is resolved against the manifest's own directory, so an absolute
    path or one containing `..` would let a file we did not write name any file on the
    machine that the validating process can read.

    Shared by every path field rather than written per field. It was written once, inline,
    for `audio.path`, and `meta.redaction_log` was added later without it, which is exactly
    the failure this function exists to stop repeating.

    Any drive is rejected, not only an absolute path: `D:recording.wav` is drive-relative,
    so Windows does not call it absolute, yet joined onto a dataset on `C:` it names a file
    on `D:`. This is the string half; `vakforge.validate` resolves the path and checks it
    again, which is the only way to see a symlink.
    """
    if not value.strip():
        raise ValueError(f"{field} is empty")
    posix = PurePosixPath(value.replace("\\", "/"))
    windows = PureWindowsPath(value)
    if posix.is_absolute() or windows.is_absolute() or windows.drive:
        raise ValueError(f"{field} must be relative to the manifest, got {value!r}")
    if ".." in posix.parts:
        raise ValueError(f"{field} must not contain '..', got {value!r}")
    return value


class Audio(_Strict):
    path: str
    sample_rate: int = 24000
    channels: int = Field(ge=1, le=2)
    channel_map: dict[str, Speaker] | None = None
    duration_s: float = Field(ge=0)
    condition: Condition = "clean"

    @model_validator(mode="after")
    def _path_stays_inside_the_dataset(self) -> Audio:
        dataset_relative(self.path, "audio.path")
        return self

    @model_validator(mode="after")
    def _channel_map_matches(self) -> Audio:
        if self.channels == 2 and self.channel_map is None:
            raise ValueError("stereo audio needs channel_map, e.g. {'0': 'user', '1': 'agent'}")
        if self.channel_map is None:
            return self
        if set(self.channel_map) != {str(i) for i in range(self.channels)}:
            raise ValueError(f"channel_map keys must be {[str(i) for i in range(self.channels)]}")
        if self.channels == 2 and set(self.channel_map.values()) != {"user", "agent"}:
            # Two channels of the same speaker cannot be split into a conversation, and the
            # convention in docs/DATA_FORMAT.md is channel 0 user, channel 1 agent.
            raise ValueError(
                "stereo channel_map must map one channel to 'user' and the other to 'agent', "
                f"got {self.channel_map}"
            )
        return self


class Language(_Strict):
    primary: str
    mix: list[str] = Field(default_factory=list)


class Tool(_Strict):
    name: str
    description: str = ""
    parameters: dict[str, Any] = Field(default_factory=lambda: {"type": "object"})


class ToolCall(_Strict):
    id: str
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class ToolResult(_Strict):
    id: str
    # Any JSON value. A real tool returns a list of matches, a bare string, a number or
    # null as readily as an object, and forcing those into a dict misrepresents what the
    # model was actually shown at training time.
    content: Any = Field(default_factory=dict)


class Entity(_Strict):
    type: str
    text: str
    start_char: int | None = None
    end_char: int | None = None
    normalized: Any = None


class Turn(_Strict):
    speaker: Speaker
    start: float = Field(ge=0)
    end: float = Field(ge=0)
    text: str | None = None
    lang: str | None = None
    # Every language in this turn, primary first. A Hinglish turn is genuinely two
    # languages, and code-switch WER (which docs/EVALUATION.md reports) can only be
    # scored on turns that say so. `lang` alone cannot express it.
    lang_mix: list[str] = Field(default_factory=list)
    entities: list[Entity] = Field(default_factory=list)
    overlap: bool = False
    tool_call: ToolCall | None = None
    tool_result: ToolResult | None = None

    @property
    def spoken(self) -> bool:
        return self.tool_call is None and self.tool_result is None

    @model_validator(mode="after")
    def _shape(self) -> Turn:
        if self.end < self.start:
            raise ValueError(f"end ({self.end}) < start ({self.start})")
        if self.tool_call and self.tool_result:
            raise ValueError("a turn carries either tool_call or tool_result, not both")
        if self.tool_call and self.speaker != "agent":
            raise ValueError("tool_call turns must have speaker='agent'")
        if self.tool_result and self.speaker != "tool":
            raise ValueError("tool_result turns must have speaker='tool'")
        if self.speaker == "tool" and not self.tool_result:
            raise ValueError("speaker='tool' turns must carry tool_result")
        if self.spoken:
            if not self.text:
                raise ValueError("spoken turns need non-empty text")
            if not self.lang:
                raise ValueError("spoken turns need lang (BCP-47, e.g. 'en-US', 'hi-Latn')")
        if self.lang_mix:
            if len(set(self.lang_mix)) != len(self.lang_mix):
                raise ValueError(f"lang_mix has repeats: {self.lang_mix}")
            if self.lang_mix[0] != self.lang:
                raise ValueError(
                    f"lang_mix[0] is {self.lang_mix[0]!r} but lang is {self.lang!r}; "
                    "the primary language comes first"
                )
        self._check_entities()
        return self

    def _check_entities(self) -> None:
        """Offsets, when given, must point at the entity's own text.

        Redaction and entity-level evaluation both slice `text` by these offsets, so an
        offset that is stale or off by a character silently corrupts the record.

        No message here repeats the text it is complaining about. The declared entity types
        are `phone`, `person_name`, `address`, `customer_id`, personal data by definition,
        and these errors are printed to a terminal and copied into CI logs and bug reports.
        `vakforge.validate` holds the same line when it reports a redaction leak.
        """
        for i, e in enumerate(self.entities):
            where = f"entities[{i}]"
            if (e.start_char is None) != (e.end_char is None):
                raise ValueError(f"{where}: set both start_char and end_char, or neither")
            if e.start_char is None:
                continue
            if e.start_char < 0 or e.end_char < e.start_char:
                raise ValueError(f"{where}: start_char={e.start_char} end_char={e.end_char}")
            text = self.text or ""
            if e.end_char > len(text):
                raise ValueError(f"{where}: end_char {e.end_char} is past the end of text")
            if text[e.start_char : e.end_char] != e.text:
                raise ValueError(
                    f"{where}: the {e.end_char - e.start_char} characters at "
                    f"[{e.start_char}:{e.end_char}] are not the {len(e.text)} in "
                    f"{where}.text; fix the offsets or the text, they disagree"
                )


RedactedField = Literal["text", "system_prompt", "tool_call.arguments", "tool_result.content"]


class AudioRedaction(_Strict):
    """Where in the recording a span was silenced or masked, and how."""

    start_s: float = Field(ge=0)
    end_s: float = Field(ge=0)
    method: Literal["tone", "silence", "noise"]

    @model_validator(mode="after")
    def _ordered(self) -> AudioRedaction:
        if self.end_s <= self.start_s:
            raise ValueError(f"end_s ({self.end_s}) must be after start_s ({self.start_s})")
        return self


class RedactionSpan(_Strict):
    """One thing a redaction pass removed, where it was, and what was left in its place.

    `placeholder` is required because it is the only part of a span that can be checked
    against the record: a span that names no placeholder cannot be told apart from one
    that describes a redaction that never ran. `{"type": "phone"}` used to pass.
    """

    type: str
    field: RedactedField = "text"
    turn: int | None = Field(default=None, ge=0)
    placeholder: str = Field(min_length=1)
    start: int | None = None
    end: int | None = None
    audio: AudioRedaction | None = None

    @model_validator(mode="after")
    def _located(self) -> RedactionSpan:
        if self.field == "system_prompt" and self.turn is not None:
            raise ValueError("a system_prompt span belongs to no turn; drop `turn`")
        if self.field != "system_prompt" and self.turn is None:
            raise ValueError(f"a {self.field} span needs `turn`, the turn it was removed from")
        if (self.start is None) != (self.end is None):
            raise ValueError("set both start and end, or neither")
        if self.start is not None and (self.start < 0 or self.end < self.start):
            raise ValueError(f"start={self.start} end={self.end}")
        return self


class RedactionLog(_Strict):
    """What a redaction pass says it removed from one conversation.

    `conversation_id` is required: without it a log copied from another conversation
    reads as evidence about this one, and nothing can tell the difference.

    An empty `spans` list is legitimate (a conversation may genuinely contain no personal
    data) and is not treated as a failed claim. The substantive check is the rescan in
    `vakforge.validate`, which reads the text itself; this model checks that the log is
    internally coherent and actually describes the record it is attached to.
    """

    conversation_id: str = Field(min_length=1)
    spans: list[RedactionSpan]


class Transcription(_Strict):
    engine: str
    verified_by_human: bool = False


class Diarization(_Strict):
    engine: str
    confidence: float = Field(ge=0, le=1, default=1.0)


class Meta(_Strict):
    source: Source
    consent: Consent
    consent_ref: str | None = None
    # What this row may be trained for. Ordinary uses are the default because that is what
    # a recording is normally collected for; `voice_clone` is the one that needs the
    # speaker's separate agreement, so it has to be asked for explicitly.
    allowed_uses: list[AllowedUse] = Field(
        default_factory=lambda: ["asr", "workflow", "evaluation"]
    )
    voice_consent_ref: str | None = None
    license: str | None = None
    pii_redacted: bool
    redaction_log: str | None = None
    transcription: Transcription | None = None
    diarization: Diarization | None = None
    split: Split
    created: datetime

    @model_validator(mode="after")
    def _provenance_is_evidenced(self) -> Meta:
        """Consent and redaction claims must carry what backs them up.

        These fields are the only record of whether a row may lawfully be trained on, so an
        unsupported claim fails the record rather than passing quietly. Synthetic rows are
        exempt from the redaction rules because they contain no real person's data.
        """
        if self.consent in ("recorded_verbal", "written") and not self.consent_ref:
            raise ValueError(
                f"consent={self.consent!r} needs consent_ref pointing at the recording or form"
            )
        if self.consent == "public_license" and not self.license:
            raise ValueError("consent='public_license' needs license (the licence it is under)")
        if self.consent == "synthetic" and self.source != "synthetic":
            raise ValueError(
                f"consent='synthetic' is only valid with source='synthetic', not {self.source!r}"
            )
        if self.redaction_log:
            dataset_relative(self.redaction_log, "meta.redaction_log")
        if not self.allowed_uses:
            raise ValueError("allowed_uses is empty, so this row may not be trained on at all")
        if (
            "voice_clone" in self.allowed_uses
            and self.source == "real"
            and not self.voice_consent_ref
        ):
            # Cloning a real person's voice is the use that needs their separate agreement.
            # Consent to record a call is not consent to reproduce the caller's voice.
            raise ValueError(
                "allowed_uses includes 'voice_clone' on real audio, which needs "
                "voice_consent_ref: the speaker's own agreement to their voice being used"
            )
        if self.source == "real":
            if not self.pii_redacted:
                raise ValueError(
                    "real data must be redacted before it enters a dataset; run `vakforge prepare`"
                )
            if not self.redaction_log:
                raise ValueError(
                    "pii_redacted=true on real data needs redaction_log naming what was removed"
                )
        return self


class Conversation(_Strict):
    """One conversation. Audio is optional: records built from documents, tables or chat
    logs have no recording until `synth` renders one."""

    id: str
    # Pinned, not free text: a row claiming a version this code has never seen cannot be
    # read safely, and accepting it quietly is how a format migration corrupts a dataset.
    schema_version: Literal["0.1"] = SCHEMA_VERSION
    audio: Audio | None = None
    locale: str
    language: Language
    domain: str | None = None
    scenario: str | None = None
    system_prompt: str | None = None
    tools: list[Tool] = Field(default_factory=list)
    turns: list[Turn] = Field(min_length=1)
    meta: Meta

    @model_validator(mode="after")
    def _cross_turn_rules(self) -> Conversation:
        prev_start = -1.0
        for i, t in enumerate(self.turns):
            if t.start < prev_start:
                raise ValueError(f"turns[{i}]: turns must be sorted by start")
            prev_start = t.start
            # `overlap` has one definition: this turn starts before the previous one ends
            # so it is checked against the timestamps rather than believed. Duplex eval
            # counts these turns, and a hand-set flag that disagrees with the clock would
            # quietly skew the interruption metrics.
            if i:
                starts_early = t.start < self.turns[i - 1].end
                if t.overlap != starts_early:
                    raise ValueError(
                        f"turns[{i}]: overlap={t.overlap} but this turn starts at "
                        f"{t.start}s and the previous ends at {self.turns[i - 1].end}s"
                    )

        tool_names: set[str] = set()
        for i, tool in enumerate(self.tools):
            if tool.name in tool_names:
                # Two schemas under one name make every call to it ambiguous, and the
                # generated tool wrapper would silently use whichever came last.
                raise ValueError(f"tools[{i}]: duplicate tool name {tool.name!r}")
            tool_names.add(tool.name)

        # A call has a lifecycle: issued once, answered at most once, and answered before
        # the conversation ends. A duplicate answer or a call left hanging teaches the
        # model a turn pattern that cannot happen at serving time.
        answered: set[str] = set()
        call_ids: set[str] = set()
        for i, t in enumerate(self.turns):
            if t.tool_call:
                if t.tool_call.id in call_ids:
                    raise ValueError(f"turns[{i}]: duplicate tool_call id {t.tool_call.id!r}")
                call_ids.add(t.tool_call.id)
                if t.tool_call.name not in tool_names:
                    raise ValueError(
                        f"turns[{i}]: tool_call {t.tool_call.name!r} not declared in tools"
                    )
            if t.tool_result:
                if t.tool_result.id not in call_ids:
                    raise ValueError(
                        f"turns[{i}]: tool_result references unknown call id {t.tool_result.id!r}"
                    )
                if t.tool_result.id in answered:
                    raise ValueError(
                        f"turns[{i}]: tool_call {t.tool_result.id!r} already has a result"
                    )
                answered.add(t.tool_result.id)
        # A trailing unanswered call is allowed: real transcripts get cut off mid-exchange,
        # and rejecting those would push people to invent a result. A call left hanging
        # while the conversation carries on is the actual defect.
        trailing = self.turns[-1].tool_call.id if self.turns[-1].tool_call else None
        if unanswered := call_ids - answered - {trailing}:
            raise ValueError(
                f"tool_call(s) {sorted(unanswered)} never get a result, and the "
                "conversation continues past them"
            )

        if self.audio and self.turns:
            last_end = max(t.end for t in self.turns)
            if last_end > self.audio.duration_s + 0.5:
                raise ValueError(
                    f"turns end at {last_end}s but audio.duration_s is {self.audio.duration_s}s"
                )

        # Whether a recording needs the speaker's own voice consent depends on what it is
        # for, which `meta.allowed_uses` says and this level cannot infer. The rule lives
        # there. It used to sit here and demanded voice_consent_ref for every real
        # recording, including audio only ever used to train recognition: a rule broad
        # enough that the easiest way past it is a dummy value, which is worse than none.
        return self


def json_schema() -> dict[str, Any]:
    """JSON Schema for one `vakforge.jsonl` line, for external validators."""
    schema = Conversation.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["title"] = f"vakforge conversation v{SCHEMA_VERSION}"
    return schema
